name: "Funda Tracker"
description: "Scrapes your estimated house value from Funda Mijn Huis and tracks it as a sensor"
version: "1.0.1"
slug: funda-tracker
url: "https://github.com/Rediwed/ha-addon-funda-tracker"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
homeassistant_api: true
options:
  funda_email: ""
  funda_password: ""
  schedule_day: 10
  schedule_hour: 10
schema:
  funda_email: email
  funda_password: password
  schedule_day: "int(1,28)"
  schedule_hour: "int(0,23)"
map:
  - type: addon_config
    read_only: true
  - type: share
    read_only: false
